import { defineConfig, devices } from "@playwright/test";
import { config as loadEnv } from "dotenv";
import path from "node:path";

// Specs seed data + log in via the service-role key. Load the same .env.local
// the app + integration tests use (generated by `node scripts/dev-env.mjs`
// after `supabase start`). It is gitignored.
loadEnv({ path: path.resolve(process.cwd(), ".env.local") });

// When E2E_BASE_URL is set, tests run against an already-running server (e.g. a
// deploy under /engage); otherwise Playwright boots the locally-built app.
const baseURL = process.env.E2E_BASE_URL ?? "http://localhost:3000";

export default defineConfig({
  testDir: "e2e",
  // Every spec seeds its own user/workspace, so they're isolated — but the
  // single local Supabase DB is happiest with a calm, low-concurrency run.
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  timeout: 45_000,
  expect: { timeout: 10_000 },
  reporter: process.env.CI ? [["github"], ["html", { open: "never" }]] : "list",
  use: {
    baseURL,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: process.env.E2E_BASE_URL
    ? undefined
    : {
        command: "npm run start",
        url: baseURL,
        timeout: 120_000,
        reuseExistingServer: !process.env.CI,
      },
});
