#!/usr/bin/env node
/**
 * Generate .env.local for local development from the running `supabase start` stack.
 *
 * Usage: node scripts/dev-env.mjs
 *
 * Reads `supabase status -o env` and writes the app's expected variable names.
 * Values flow subprocess -> file and are never printed. Existing non-Supabase
 * lines in .env.local (e.g. CRON_SECRET, APP_ENCRYPTION_KEY) are preserved.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";

const raw = execSync("npx supabase status -o env", { encoding: "utf8" });
const status = {};
for (const line of raw.split(/\r?\n/)) {
  const m = line.match(/^([A-Z_]+)="?([^"]*)"?$/);
  if (m) status[m[1]] = m[2];
}

const required = ["API_URL", "ANON_KEY", "SERVICE_ROLE_KEY"];
for (const k of required) {
  if (!status[k]) {
    console.error(`supabase status missing ${k} — is the stack running? (npx supabase start)`);
    process.exit(1);
  }
}

const managed = {
  NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: status.ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
  NEXT_PUBLIC_APP_URL: "http://localhost:3000",
};

const envPath = new URL("../.env.local", import.meta.url);
const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
const kept = existing
  .split(/\r?\n/)
  .filter((l) => l.trim() && !Object.keys(managed).some((k) => l.startsWith(`${k}=`)));

// First run: generate local-only dev secrets so the app boots fully configured.
if (!kept.some((l) => l.startsWith("CRON_SECRET="))) {
  kept.push(`CRON_SECRET=${randomBytes(32).toString("base64url")}`);
}
if (!kept.some((l) => l.startsWith("APP_ENCRYPTION_KEY="))) {
  kept.push(`APP_ENCRYPTION_KEY=${randomBytes(32).toString("base64")}`);
}

const out = [
  "# Generated by scripts/dev-env.mjs — local dev only, gitignored.",
  ...Object.entries(managed).map(([k, v]) => `${k}=${v}`),
  ...kept.filter((l) => !l.startsWith("# Generated by")),
  "",
].join("\n");

writeFileSync(envPath, out);
console.log(`.env.local written (${Object.keys(managed).length} supabase vars + ${kept.length} kept lines)`);
